// Cột của từng view, trích từ dashboard_export_20260814T091558/datasets/PVPUS_LIVE/*.yaml
// Dùng để biết view nào có cột ORG_NAME3 / YEAR / MONTH trước khi thêm điều kiện lọc.
module.exports = {
  DBV_AT_ABSENCE_RATE: ["ORG_NAME3","ORG_ID3","ABSENCE_RATE_PCT","ABSENCE_TOTAL","REPORT_DATE","TOTAL_WORKING_XJ_TOTAL","TOTAL_WORKING_RO_TOTAL","WORKING_BHXH_TOTAL","WORKING_P_L_CD_O_TOTAL","WORKING_CD_TOTAL","WORKING_R_DD_K_TOTAL","YEAR","WORKING_RO_TS_TOTAL","WORKING_RO_TOTAL","WORKING_O_TOTAL","ORG_CODE","ORG_ID","MONTH"],
  DBV_AT_HEALTH_SAFETY_LEAVE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","TOTAL_HEALTH_SAFETY_LEAVE_DAYS","REPORT_DATE","YEAR","ORG_CODE","WORKING_DH","ORG_ID","WORKING_TN","WORKING_O","MONTH"],
  DBV_AT_LEAVE_UTILIZATION_RATE: ["ORG_NAME3","ORG_ID3","LEAVE_UTILIZATION_RATE_PCT","TOTAL_LEAVE_DAYS","REPORT_DATE","USED_LEAVE_DAYS","YEAR","MONTH","ORG_CODE","ORG_ID"],
  DBV_AT_OT_COST: ["ORG_NAME3","ORG_ID3","OT_COST_TOTAL","OT_HOURS_CONVERTED","ORG_CODE","ORG_ID","OT_HOURS",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_AT_OT_RATE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","REPORT_DATE","OT_RATE_PCT","YEAR","TOTAL_WORKING_XJ","OT_HOURS_CONVERTED","ORG_CODE","ORG_ID","MONTH","OT_HOURS"],
  DBV_AT_TOTAL_WORKING_SALARY: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","TOTAL_WORKING_SALARY","REPORT_DATE","YEAR","TOTAL_WORKING_XJ","WORKING_NB","ORG_CODE","WORKING_CD","ORG_ID","WORKING_L","WORKING_P","WORKING_R","MONTH"],
  DBV_AT_UTILIZATION_RATE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","UTILIZATION_RATE_PCT","WORKING_ACTUAL_HOURS","REPORT_DATE","WORKING_STANDARD_HOURS","YEAR","ORG_CODE","ORG_ID","MONTH"],
  dbv_count_employee: ["EMPLOYEE_NAME","EMPLOYEE_ID","ORG_NAME3",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  dbv_fte: ["EMPLOYEE_COUNT", "ORG_NAME3",
    "YEAR", 
    "MONTH", 
    "REPORT_DATE"
  ],
  DBV_HR_LABOR_COST: ["ORG_NAME3","ORG_NAME4","OBJ_SALARY_ID","REPORT_DATE","THUONG_AN_TOAN","CHI_PHI_BAO_HIEM_CTY","THU_NHAP_BO_SUNG","CHI_PHI_CONG_DOAN_CTY","YEAR","LUONG_THANG","ORG_CODE","PERIOD_ID","ORG_ID","LUONG_KKNS","MONTH","CHI_PHI_NHAN_CONG","LUONG_HIEU_QUA"],
  DBV_HU_EMPLOYEE_AGE_STATISTICS: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","AGE_GROUP_NAME","ORG_CODE","EMPLOYEE_COUNT","ORG_ID","PERCENT_IN_ORG",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_APPOINTMENT_RATE: ["ORG_ID","ORG_CODE","ORG_ID3","ORG_NAME3","EMPLOYEE_COUNT_APPOINTED","MANAGEMENT_POSITION_NEW_EMPLOYEE_COUNT","APPOINTMENT_RATE_PCT",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_AVERAGE_AGE: ["ORG_NAME3","ORG_ID3","EMPLOYEE_COUNT_WITH_BIRTH_DATE","EMPLOYEE_COUNT_TOTAL","ORG_CODE","ORG_ID","AVG_AGE",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_AVERAGE_SENIORITY: ["ORG_NAME3","ORG_ID3","EMPLOYEE_COUNT_WITH_JOIN_DATE_STATE","EMPLOYEE_COUNT_TOTAL","ORG_CODE","ORG_ID","AVG_SENIORITY_YEARS",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_ENGINEER_TECH_RATE: ["ORG_NAME3","ORG_ID3","ORG_CODE","EMPLOYEE_COUNT","ORG_ID","EMPLOYEE_GROUP",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_FTE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","EXCLUDED_LEAVE_COUNT","EMPLOYEE_COUNT_ACTIVE","FTE_COUNT_TOTAL","ORG_CODE","ORG_ID",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_HEADCOUNT: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","EMPLOYEE_COUNT_TOTAL","ORG_CODE","ORG_ID",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_INTERNAL_TRANSFER_RATE: ["ORG_NAME3","ORG_ID3","REPORT_DATE","EMPLOYEE_COUNT_CHANGED","EMPLOYEE_COUNT_TOTAL","YEAR","ORG_CODE","ORG_ID","MONTH","INTERNAL_TRANSFER_RATE_PCT"],
  DBV_HU_EMPLOYEE_LEARNING_LEVEL_STATISTICS: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","LEARNING_LEVEL_NAME","LEARNING_LEVEL","ORG_CODE","EMPLOYEE_COUNT","ORG_ID","PERCENT_IN_ORG"],
  DBV_HU_EMPLOYEE_NEW_HIRE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","REPORT_DATE","YEAR","ORG_CODE","EMPLOYEE_COUNT_NEW_HIRE","ORG_ID","MONTH"],
  DBV_HU_EMPLOYEE_SALARY_INCREASE_RATE: ["ORG_NAME3","ORG_ID3","AVG_SALARY_INCREASE_AMOUNT","AVG_CURRENT_SAL_TOTAL","AVG_PREV_SAL_TOTAL","REPORT_DATE","EMPLOYEE_COUNT_INCREASED","YEAR","ORG_CODE","ORG_ID","MONTH","AVG_SALARY_INCREASE_PCT"],
  DBV_HU_EMPLOYEE_SENIORITY_STATISTICS: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","SENIORITY_GROUP_NAME","ORG_CODE","EMPLOYEE_COUNT","ORG_ID","PERCENT_IN_ORG",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_EMPLOYEE_TERMINATION: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","REPORT_DATE","EMPLOYEE_COUNT_TERMINATION","YEAR","ORG_CODE","ORG_ID","MONTH"],
  DBV_HU_EMPLOYEE_TERMINATION_RATE: ["ORG_NAME3","ORG_ID3","REPORT_DATE","EMPLOYEE_COUNT_TERMINATION","EMPLOYEE_COUNT_TOTAL","YEAR","ORG_CODE","ORG_ID","MONTH","TERMINATION_RATE_PCT"],
  DBV_HU_MANAGER_SPAN_OF_CONTROL: ["ORG_NAME3","ORG_ID3","EMPLOYEE_COUNT_UNDER_MANAGER","MANAGER_COUNT","ORG_CODE","ORG_ID","AVG_SPAN_OF_CONTROL", "DIRECT_MANAGER_COUNT",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_HU_WAGE_AVERAGE_EMPLOYEE: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","TOTAL_SALARY","EMPLOYEE_COUNT_TOTAL","ORG_CODE","ORG_ID","AVERAGE_SALARY",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  dbv_pa_financial_profit_employee: ["ORG_NAME3","ORG_NAME4","FINANCIAL_INDICATOR_ID","CREATED_DATE","MODIFIED_DATE","REPORT_DATE","SALARY_FUND","CREATED_BY","EMPLOYEE_COUNT_ACTIVE","CREATED_LOG","EMPLOYEE_COUNT_TOTAL","REVENUE_AMOUNT","YEAR","PROFIT_AMOUNT","MODIFIED_BY","ORG_CODE","MODIFIED_LOG","ORG_ID","NET_REVENUE","PROFIT_PER_EMPLOYEE_ACTIVE","PROFIT_PER_EMPLOYEE_TOTAL"],
  DBV_PA_FINANCIAL_REVENUE_EMPLOYEE: ["EMPLOYEE_COUNT_ACTIVE","REVENUE_PER_EMPLOYEE_ACTIVE","EMPLOYEE_COUNT_TOTAL","REVENUE_PER_EMPLOYEE_TOTAL","ORG_CODE","ORG_NAME3","ORG_NAME4","FINANCIAL_INDICATOR_ID","CREATED_DATE","SALARY_FUND","CREATED_BY","CREATED_LOG","MODIFIED_DATE","REPORT_DATE","REVENUE_AMOUNT","YEAR","PROFIT_AMOUNT","MODIFIED_BY","MODIFIED_LOG","ORG_ID","NET_REVENUE"],
  DBV_PA_FINANCIAL_SALARY_FUND_REVENUE: ["ORG_NAME3","ORG_NAME4","FINANCIAL_INDICATOR_ID","CREATED_DATE","SALARY_FUND_REVENUE_AMOUNT_PCT","SALARY_FUND_NET_REVENUE_PCT","MODIFIED_DATE","SALARY_FUND","CREATED_BY","CREATED_LOG","REVENUE_AMOUNT","PROFIT_AMOUNT","MODIFIED_BY","ORG_CODE","MODIFIED_LOG","ORG_ID","NET_REVENUE",
    "YEAR",
    "MONTH",
    "REPORT_DATE"
  ],
  DBV_PA_PAYROLL_TOTAL_INCOME: ["ORG_NAME3","ORG_ID3","ORG_NAME4","ORG_ID4","TOTAL_INCOME_AMOUNT","REPORT_DATE","PAYROLL_ROW_COUNT","YEAR","ORG_CODE","ORG_ID","MONTH"],
};
